import json

data = json.loads(open('cookie', 'r').read())
write = open('saved', 'w')
write.write("# Netscape HTTP Cookie File\n# https://curl.haxx.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n")

for x in data:
    if x["httpOnly"]:
        write.write("#HttpOnly_")
    write.write(x["domain"] + '\t' + str(x["httpOnly"]) + '\t' + x["path"] + '\t' + str(x["secure"]) + '\t' + x["name"] + '\t' + x["value"] + '\n')
    

