import json

data = json.loads(open('cookie', 'r').read())
write = open('saved', 'w')
write.write("# Netscape HTTP Cookie File\n# https://curl.haxx.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n")

def boolToString(s):
    if s:
        return "TRUE"
    else:
        return "FALSE"

def checkTailMatch(s):
    if s[0] == ".":
        return "TRUE"
    return "FALSE"

for x in data:
    if x["httpOnly"]:
        write.write("#HttpOnly_")
    write.write(x["domain"] + '\t' + checkTailMatch(x["domain"]) + '\t' + x["path"] + '\t' + boolToString(x["secure"]) + '\t' + "0" + '\t' + x["name"] + '\t' + x["value"] + '\n')

    

